# Image de base qui contient tous les outils de compilation que nous voulons pour ARM.
FROM gcc
#FROM arm64v8/ubuntu

# Ce qui se situe dans le dossier .devcontainer/tools est copié dans le container sous /root/.../tools
COPY ./tools /root/SOURCES/ift209/tools