# --platform=linux/arm64/v8 is required to find the proper file.
#FROM --platform=linux/arm64/v8 arm64v8/ubuntu
FROM gcc
#FROM arm64v8/ubuntu

#SHELL ["/bin/bash", "-c"] # Works without this line...

# The following line is required for the devcontainer to work.
# CMD ["tail", "-f", "/dev/null"]